sudo: false

language: node_js

node_js:
  - "10"
  - "12"
  - "13"
  - "node"

cache:
  directories:
    - node_modules
    - $HOME/.npm

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    node: "node"
